# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'BoxedSoul' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoxedSoul
	pod "TheAmazingAudioEngine"
pod 'Alamofire', '~> 3.4'    
pod 'AWSCognito'
    pod 'AWSS3'
    pod 'AWSSNS'
end
